app:
  platform: react_native        # or ios_native / android_native
  testid_to_logical:
    product_sku_hoodie: us.mappings.yourOrders.hoodieProduct
    product_sku_cap:    us.mappings.yourOrders.capProduct
  ios_to_logical:
    settingsButton:     us.mappings.account.menuSettingsButton
  android_to_logical:
    com.walmart.android.debug:id/account_header_settings: us.mappings.account.menuSettingsButton
    product_sku_hoodie: us.mappings.yourOrders.hoodieProduct

llm:
  provider: rulebased   # openai | anthropic | rulebased
  openai_api_key: "${OPENAI_API_KEY:-}"
  anthropic_api_key: "${ANTHROPIC_API_KEY:-}"
  model: "gpt-4o"
  temperature: 0.1

vectordb:
  provider: local
  api_key: ""
  index_name: "autoheal-failures"
  base_path: "./vector_index"

vcs:
  provider: local
  github_token: "${GITHUB_TOKEN:-}"
  repo: "idcmurali1/Automation-test-framework-HOB"

ci:
  provider: local

artifact_store:
  path: "./artifacts"

policy:
  file: "./policies/policy.yaml"

logging:
  level: "INFO"
  patch_ledger: "./patches/ledger.jsonl"

source_files:
  react_native:
    - "src/catalog.ts"
    - "src/menu.ts"
  ios_native:
    - "ios/Views/ProductView.swift"
    - "ios/Controllers/MenuController.swift"
  android_native:
    - "android/app/src/main/java/com/walmart/app/CatalogActivity.java"
    - "android/app/src/main/java/com/walmart/app/MenuActivity.java"
