app:
  platform: react_native  # or ios_native / android_native

  # Exact RN testID -> logical (highest priority)
  testid_to_logical:
    product_sku_hoodie:  us.mappings.yourOrders.hoodieProduct
    product_sku_cap:     us.mappings.yourOrders.capProduct

  # Flexible families (regex). Your *_val1 change is covered here.
  testid_patterns:
    - match: "^product_sku_hoodie.*$"
      logical: us.mappings.yourOrders.hoodieProduct
    - match: "^product_sku_cap.*$"
      logical: us.mappings.yourOrders.capProduct
    - match: "^product_sku_shirt.*$"
      logical: us.mappings.yourOrders.shirtProduct

  ios_patterns:
    - match: "^(settingsButton|.*SettingsButton.*)$"
      logical: us.mappings.account.menuSettingsButton

  # Split menu vs product patterns (don’t map hoodie to menu!)
  android_patterns:
    - match: "^com\\.walmart\\.android\\.debug:id/account_header_settings.*$"
      logical: us.mappings.account.menuSettingsButton
    - match: "^product_sku_hoodie.*$"
      logical: us.mappings.yourOrders.hoodieProduct
    - match: "^product_sku_cap.*$"
      logical: us.mappings.yourOrders.capProduct

source_files:
  react_native:
    - "src/catalog.ts"
    - "src/menu.ts"
  ios_native:
    - "ios/Views/ProductView.swift"
    - "ios/Controllers/MenuController.swift"
  android_native:
    - "android/app/src/main/java/com/walmart/app/CatalogActivity.java"
    - "android/app/src/main/java/com/walmart/app/MenuActivity.java"

llm:
  provider: rulebased
  openai_api_key: "${OPENAI_API_KEY:-}"
  anthropic_api_key: "${ANTHROPIC_API_KEY:-}"
  model: "gpt-4o"
  temperature: 0.1

vectordb:
  provider: local
  api_key: ""
  index_name: "autoheal-failures"
  base_path: "./vector_index"

vcs:
  provider: local
  github_token: "${GITHUB_TOKEN:-}"
  repo: "idcmurali1/Automation-test-framework-HOB"

ci:
  provider: local

artifact_store:
  path: "./artifacts"

policy:
  file: "./policies/policy.yaml"

logging:
  level: "INFO"
  patch_ledger: "./patches/ledger.jsonl"
